apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  APP_ENV: development
  APP_NAME: Nel-Nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
stringData:
  DB_USER: neluser
  DB_PASSWORD: CHANGE_ME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-config-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-config-secret
  template:
    metadata:
      labels:
        app: nginx-config-secret
    spec:
      containers:
      - name: nginx
        image: nel-nginx:v2
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: APP_ENV
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: APP_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: DB_PASSWORD
